variable "network_name" {
  type        = string
  description = "The name of the network resources: should be generated by provider/universal/name-generator"
}

variable "network_id" {
  type        = string
  description = "The id of the cloud provider network ID resource"
}

variable "network_cidr" {
  type        = string
  description = "The network cidr address space"
}

variable "network_dns" {
  type        = string
  description = "The ID for the internal DNS zone"
}

variable "region" {
  type        = string
  description = "The Azure region to deploy environment"
}

variable "locations" {
  type        = tolist(string)
  description = "The Azure availability zones to deploy environment"
}

variable "public_key_path" {
  type        = string
  description = "The path to the public key for SSH access"
}

variable "private_key_path" {
  type        = string
  description = "The path to the private key for SSH access"
}

variable "additional_public_keys_path" {
  type        = string
  default     = ""
  description = "The path to a file that contains multiple public keys for SSH access."
}

variable "user_name" {
  type        = string
  description = "The user name of the remote hosts"
}

variable "subnet_id" {
  type        = string
  description = "The subnet ID to launch bastion host. Should be a public subnet"
}

variable "trigger" {
  type        = string
  default     = ""
  description = "A trigger key that will initiate provisioning of bastion resource"
}

variable "resource_type" {
  type        = string
  description = "The resource type of the bastion instance"
}

variable "resource_count" {
  type        = string
  description = "The number of bastion resources to create"
}

variable "resource_root_volume_size" {
  type        = string
  description = "The root volume size of bastion instance"
}

variable "bastion_access_cidr" {
  type        = string
  description = "You can limit access to the bastion node to a specified IP cidr range"
}

variable "image_id" {
  type        = string
  description = "The image id to initiate"
}

variable "vm_os_publisher" {
  type        = string
  description = "The image os publisher"
  default     = ""
}

variable "vm_os_offer" {
  type        = string
  description = "The image os offer"
  default     = ""
}

variable "vm_os_sku" {
  type        = string
  description = "The image os sku"
  default     = ""
}

variable "enable_tdagent" {
  type        = bool
  description = "A flag to install td-agent that forwards logs to the monitor host"
}

variable "enable_accelerated_networking" {
  type        = bool
  default     = false
  description = "A flag to enable accelerated networking on network interface"
}
