---
- name: Reload td-agent
  systemd:
    name: td-agent
    state: reloaded

- name: Restart td-agent
  systemd:
    name: td-agent
    state: restarted

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
