---
- import_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install required packages via pip
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - j2cli
  environment:
    PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin

- name: Install nessnecessary packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - lvm2
  retries: 3
  delay: 5
