---
- import_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Upgrade pip
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install required packages via pip
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  loop: "{{ pip_packages }}"

- name: Install required packages
  package:
    name: "{{ required_packages }}"
    state: present
  retries: 3
  delay: 5
