---
- name: Install epel-release
  package:
    name: epel-release
    state: present

- name: Install python (redhat)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-devel
    - python3-pip
