---
- name: Create Cassandra User
  user:
    create_home: yes
    name: cassandra

- name: Add Cassy Public Key
  authorized_key:
    user: cassandra
    key: "{{ lookup('file', './cassandra.pub') }}"
    manage_dir: True

- name: Create Cassy Log Directory
  file:
    path: /var/log/scalar
    owner: cassandra
    state: directory

- name: Create Cassandra Profile Directory
  file:
    path: /etc/tuned/cassandra
    state: directory

- name: Add Cassandra Tuned Profile
  template:
    src: tuned.conf.j2
    dest: /etc/tuned/cassandra/tuned.conf
    mode: 0600

- name: Set Active Tuned Profile to Cassandra
  command: "tuned-adm profile cassandra"

- name: Set vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    sysctl_set: yes
    state: present
    reload: yes

- name: Copy Cassy Backup Tool
  copy:
    src: cassy
    dest: /opt/
    mode: 0755

- name: Copy Drive Mount Script
  copy:
    src: drive_mount.sh
    dest: /usr/local/bin/
    mode: 0755

- name: Copy Drive Mount Service
  copy:
    src: drivemount.service
    dest: /etc/systemd/system/drivemount.service
    mode: 0600

- name: Setup Drive Mount Service
  systemd:
    name: drivemount
    enabled: yes
    daemon_reload: yes
    state: started

- name: Add Cassandra Repo Debian
  lineinfile:
    line: "deb https://downloads.apache.org/cassandra/debian 311x main"
    path: /etc/apt/sources.list.d/cassandra.sources.list
    create: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Add Keys
  shell: curl https://downloads.apache.org/cassandra/KEYS | apt-key add -
  when: ansible_facts['os_family'] == "Debian"

- name: Apt Update
  shell: apt update
  when: ansible_facts['os_family'] == "Debian"

- name: Add Cassandra Repo
  copy:
    src: cassandra.repo
    dest: /etc/yum.repos.d/cassandra.repo
    mode: 0600
  when: ansible_facts['os_family'] == "RedHat"

- name: Install jemalloc
  package:
    name: jemalloc
    state: present
  register: install_jemalloc_result
  until: install_jemalloc_result is succeeded
  retries: 3
  delay: 5

- name: Install Cassandra
  package:
    name: cassandra
    state: present
  register: install_cassandra_result
  until: install_cassandra_result is succeeded
  retries: 3
  delay: 5

- name: Set Cassandra Auth JMX
  lineinfile:
    line: -Dcom.sun.management.jmxremote.authenticate=false
    path: /etc/cassandra/conf/jvm.options

- name: Set Cassandra JMX Port
  lineinfile:
    line: -Dcassandra.jmx.remote.port=7199
    path: /etc/cassandra/conf/jvm.options

- name: Set Cassandra JMX Port
  lineinfile:
    line: -Dcom.sun.management.jmxremote.rmi.port=7199
    path: /etc/cassandra/conf/jvm.options

- name: Set JVM Memory Options
  blockinfile:
    path: /etc/cassandra/conf/jvm.options
    block: |
      -Xms{{ ((ansible_memtotal_mb|int / 2) / 1024)|round|int}}G
      -Xmx{{ ((ansible_memtotal_mb|int / 2) / 1024)|round|int}}G
      -Xmn{{ ansible_processor_vcpus|int * 100}}M

- name: Copy Cassandra Config
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/conf/cassandra.yaml
    mode: 0644

- name: Copy cassandra-rackdc.properties
  template:
    src: cassandra-rackdc.properties.j2
    dest: /etc/cassandra/conf/cassandra-rackdc.properties
    mode: 0644

- name: Disable debug.log
  replace:
    path: /etc/cassandra/conf/logback.xml
    regexp: '^\s*(<appender-ref ref="ASYNCDEBUGLOG"\s*/>)'
    replace: '<!-- \1 -->'

- name: Delete cassandra-topology.properties
  file:
    path: /etc/cassandra/conf/cassandra-topology.properties
    state: absent

- name: Setup Cassandra Service
  systemd:
    name: cassandra
    enabled: yes
    daemon_reload: yes
    state: "{{ CASSANDRA_STATE }}"

- name: Install Tools
  block:
    - file:
        path: "/etc/prometheus"
        state: directory
        mode: 0755
    - get_url:
        url: https://github.com/criteo/cassandra_exporter/releases/download/2.1.0/cassandra_exporter-2.1.0-all.jar
        dest: /etc/prometheus/cassandra_exporter.jar
        mode: 0600
    - copy:
        src: cassandra_exporter_config.yml
        dest: /etc/prometheus/cassandra_exporter_config.yml
        mode: 0600
    - copy:
        src: cassandra_exporter.service
        dest: /etc/systemd/system/cassandra_exporter.service
        mode: 0600
    - systemd:
        name: cassandra_exporter
        enabled: yes
        daemon_reload: yes
        state: started
