---
- name: test if additional_public_keys file exists
  local_action:
    module: stat
    path: "files/ssh/additional_public_keys"
  register: files_detail

- name: add key
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', 'files/ssh/additional_public_keys') }}"
  when: files_detail.stat.exists == true
