---
- name: Bastion server
  hosts: all
  roles:
    - "common"
    - "ansible"
    - role: td-agent
      when: enable_tdagent is undefined or enable_tdagent == '1'
  vars:
    tdagent_conf_template: templates/cassandra-server/td-agent.conf.j2
  gather_facts: no
  become: yes

- name: Set up multiple authorized keys
  hosts: all
  gather_facts: false
  become: false
  roles:
    - "ssh"
  tags:
  - ssh