---
- name: Bastion server
  hosts: all
  pre_tasks:
    - name: Switch Ansible's Python interpreter to Python 3
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - common
    - node-exporter
    - ansible
    - role: td-agent
      when: enable_tdagent is undefined or enable_tdagent == '1'
  vars:
    tdagent_confd_templates:
      - { src: "templates/td-agent-confd/td-agent-bastion.conf.j2", dest: "bastion.conf" }
      - { src: "templates/td-agent-confd/metrics.conf.j2", dest: "metrics.conf" }
  gather_facts: yes
  become: yes

- name: Add multiple public keys
  hosts: all
  gather_facts: no
  become: no
  roles:
    - ssh
  tags:
    - ssh
