---
# tasks file for ansible-role-td-agent
- import_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install td-agent
  package:
    name: td-agent
    state: present

- name: Install td-agent plugins
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: /usr/sbin/td-agent-gem
    user_install: no
    state: present
  loop: "{{ td_agent_plugins }}"
  notify: Restart td-agent
  when: log_archive_storage_info is defined and log_archive_storage_info != ''

- name: Create conf.d directory
  file:
    path: "{{ tdagent_confd_dir }}"
    state: directory

- name: Enable td-agent
  systemd:
    name: td-agent
    enabled: yes

- name: Update rsyslog.conf to forward logs
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @127.0.0.1:5140"
  notify: Restart rsyslog

- name: Update td-agent.conf
  template:
    src: td-agent.conf.j2
    dest: "{{ tdagent_conf_dir }}/td-agent.conf"
    owner: td-agent
    group: td-agent
    mode: 0644
  notify: Reload td-agent

- name: Add user defined templates
  template:
    src: "{{ item.src }}"
    dest: "{{ tdagent_confd_dir }}/{{ item.dest }}"
    owner: td-agent
    group: td-agent
    mode: 0644
  loop: "{{ tdagent_confd_templates }}"
  notify: Reload td-agent
