---
- name: Add rpm gpg key
  rpm_key:
    key: "{{ tdagent_gpg_key }}"
    state: present
  register: rpm_key_result
  until: rpm_key_result is succeeded
  retries: 3
  delay: 5

- name: Add td-agent repository
  template:
    src: td.repo.j2
    dest: /etc/yum.repos.d/td.repo
    owner: root
    group: root
    mode: 0644
