---
- import_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'
  become: yes

- import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'
  become: yes

- name: Install Docker.
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
  notify: Restart docker
  become: yes

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: started
    enabled: true

- import_tasks: docker-users.yml
  when: docker_users | length > 0
  become: yes

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Configure Docker to use fluentd logging driver by default if td-agent is installed
  block:
    - file:
        path: /etc/docker
        state: directory
    - copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
  when: "'td-agent' in ansible_facts.packages"

- name: Install Git
  package:
    name: git
    state: present
  register: install_git_result
  until: install_git_result is succeeded
  retries: 3
  delay: 5

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: started
    enabled: true

- import_tasks: install-cadvisor.yml
  become: yes
