version: "3.7"

services:
  cassy:
    image: ghcr.io/scalar-labs/cassy:${IMAGE_TAG}
    ports:
      - "20051:20051"
    volumes:
      - ./conf:/cassy/conf
      - ./data:/cassy/data
      - ~/.ssh/cassy.pem:/opt/cassy/cassy.pem
    restart: always
