version: "3.1"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.7.1
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=${prometheus_data_retention_period_time}"
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.16.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  grafana:
    image: grafana/grafana:6.5.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  nginx:
    image: nginx:1.19.5
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxies.conf:/etc/nginx/conf.d/proxies.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    depends_on:
      - prometheus
      - alertmanager
      - grafana

  tailon:
    image: gvalkov/tailon:latest
    ports:
      - 8080:8080
    volumes:
      - /log:/tailon/log
      - ./tailon/config.toml:/tailon/config.toml
    command:
      - "-c"
      - "/tailon/config.toml"
      - "/tailon/log/*/*.log"
    restart: always
