---
cassandra_version: 3.11.9
cassandra_rpm_url: http://archive.apache.org/dist/cassandra/redhat/311x/cassandra-{{ cassandra_version }}-1.noarch.rpm
tuned_profile: virtual-guest
# Only Cassandra disks are tuned and OS disks are not tuned.
# In AWS, sda and xvda are used depending on virtualization types.
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html#available-ec2-device-names
# In Azure, sda is used for OS.
tuned_disk_devices: "!sda, !xvda, !nvme0n1"
disk_read_ahead: 8
CASSANDRA_MEMTABLE_THRESHOLD: 0.33
CASSANDRA_STATE: stopped
cassandra_dc_id: dc1
cassandra_rack_id: rack1
endpoint_snitch: GossipingPropertyFileSnitch
vm_max_map_count: "1048575"
