variable "network_name" {
  description = "The name of the network resources: should be generated by provider/universal/name-generator"
}

variable "bastion_ip" {
  description = "The IP to bastion host used for provisioning"
}

variable "network_cidr" {
  description = "The network cidr address space"
}

variable "network_id" {
  description = "The id of the cloud provider network ID resource"
}

variable "private_key_path" {
  description = "The path to the private key for SSH access"
}

variable "user_name" {
  description = "The user name of the remote hosts"
}

variable "subnet_id" {
  description = "The subnet ID to launch scalardl hosts"
}

variable "image_id" {
  description = "The image id to initiate"
}

variable "key_name" {
  description = "The key-pair name to assign to cluster resources"
}

variable "network_dns" {
  description = "The ID for the internal DNS zone"
}

variable "triggers" {
  default     = []
  description = "A trigger key that will initiate provisioning of monitor resource"
}

variable "resource_type" {
  default     = "t2.micro"
  description = "The resource type of the monitor instance"
}

variable "resource_count" {
  default     = 1
  description = "The number of resources to create"
}

variable "resource_root_volume_size" {
  default = "16"
}

variable "enable_tdagent" {
  default     = true
  description = "A flag to install td-agent that forwards logs to the monitor host"
}

