bastion:
  cpu_cores: 2
  mem: 963M
cassandra:
  cpu_cores: 2
  mem: 15G
  jvm:
    xms: 4G
    xmx: 4G
    xmn: 200M
  tuned:
    readahead: 8
    devices: "!sda, !xvda, !nvme0n1"
  nr_requests:
    nvme0n1: 31
    nvme1n1: 127
    nvme2n1: 31
  scheduler:
    nvme0n1: none
    nvme1n1: none
    nvme2n1: none
cassy:
  cpu_cores: 2
  mem: 3.6G
reaper:
  cpu_cores: 2
  mem: 3.6G
envoy:
  cpu_cores: 2
  mem: 3.6G
scalardl:
  cpu_cores: 2
  mem: 3.6G
