bastion:
  cpu_cores: 2
  mem: 963M
cassandra:
  cpu_cores: 2
  mem: 7.5G
  jvm:
    xms: 4G
    xmx: 4G
    xmn: 200M
  tuned:
    readahead: 8
    devices: "!sda, !xvda, !nvme0n1"
  nr_requests: 127
  scheduler: none
