bastion:
  cpu_cores: 1
  mem: 927M
cassandra:
  cpu_cores: 2
  mem: 15G
  jvm:
    xms: 4G
    xmx: 4G
    xmn: 200M
  tuned:
    readahead: 8
    devices: "!sda, !xvda, !nvme0n1"
  nr_requests: 256
  scheduler: none
cassy:
  cpu_cores: 2
  mem: 3.9G
reaper:
  cpu_cores: 2
  mem: 3.9G
envoy:
  cpu_cores: 2
  mem: 3.9G
scalardl:
  cpu_cores: 2
  mem: 3.9G
