---
- name: Set Zookeeper servers
  set_fact:
    zk_servers: "{{ zookeeper_servers.split(',') | map('regex_replace', '(.*)', '\\1:2181') | join(',') }}"

- name: Copy bookkeeper.conf
  template:
    src: bookkeeper.conf.j2
    dest: /opt/pulsar/conf/bookkeeper.conf

- name: Copy bookkeeper.service
  template:
    src: bookkeeper.service.j2
    dest: /etc/systemd/system/bookkeeper.service

- name: Enable bookie service
  systemd:
    state: restarted
    daemon_reload: yes
    name: bookkeeper
