---
- name: Set Zookeeper servers
  set_fact:
    zk_servers: "{{ zookeeper_servers.split(',') | map('regex_replace', '(.*)', '\\1:2181') | join(',') }}"

- name: Copy broker.conf
  template:
    src: broker.conf.j2
    dest: /opt/pulsar/conf/broker.conf

- name: Copy broker.service
  template:
    src: broker.service.j2
    dest: /etc/systemd/system/broker.service

- name: Enable bookie service
  systemd:
    state: restarted
    daemon_reload: yes
    name: broker
