---
- name: Set Zookeeper servers
  set_fact:
    servers: "{{ zookeeper_servers.split(',') |list }}"

- name: Create ZooKeeper data directory
  file:
    path: "/opt/pulsar/{{ item }}"
    state: directory
  loop:
    - data/zookeeper

- name: Add zookeeper.conf file
  template:
    src: zookeeper.conf.j2
    dest: /opt/pulsar/conf/zookeeper.conf

- name: Add myid file for ZooKeeper
  template:
    src: "zookeeper.myid.j2"
    dest: "/opt/pulsar/data/zookeeper/myid"

- name: Add zookeeper.service systemd file
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service

- name: Enable zookeeper service
  systemd:
    state: restarted
    daemon_reload: yes
    name: zookeeper

- name: Initialize cluster metadata
  shell: |
    bin/pulsar initialize-cluster-metadata \
      --cluster {{ cluster_name }} \
      --zookeeper localhost:2181 \
      --configuration-store localhost:2181 \
      --web-service-url {{ http_url }} \
      --broker-service-url {{ service_url }}
  args:
    chdir: /opt/pulsar
  when: servers[0] == inventory_hostname
