version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    environment:
      - SCALAR_DB_STORAGE=${SCALAR_DB_STORAGE}
      - SCALAR_DB_CONTACT_POINTS=${SCALAR_DB_CONTACT_POINTS}
      - SCALAR_DB_CONTACT_PORT=${SCALAR_DB_CONTACT_PORT}
      - SCALAR_DB_USERNAME=${SCALAR_DB_USERNAME}
      - SCALAR_DB_PASSWORD=${SCALAR_DB_PASSWORD}
      # SCALAR_DL_AUDITOR_* variables are used if we are running scalar-auditor
      - SCALAR_DL_AUDITOR_LEDGER_HOST=${SCALAR_DL_AUDITOR_LEDGER_HOST}
      - SCALAR_DL_AUDITOR_LEDGER_PORT=${SCALAR_DL_AUDITOR_LEDGER_PORT}
      - SCALAR_DL_AUDITOR_LEDGER_PRIVILEGED_PORT=${SCALAR_DL_AUDITOR_LEDGER_PRIVILEGED_PORT}
      - SCALAR_DL_AUDITOR_CERT_HOLDER_ID=${SCALAR_DL_AUDITOR_CERT_HOLDER_ID}
      - SCALAR_DL_AUDITOR_CERT_PEM=${SCALAR_DL_AUDITOR_CERT_PEM}
      - SCALAR_DL_AUDITOR_PRIVATE_KEY_PEM=${SCALAR_DL_AUDITOR_PRIVATE_KEY_PEM}
    ports:
      - 50051:50051 # TODO: SCALAR_PORT
      - 50052:50052 # TODO: SCALAR_PRIVILEGED_PORT
      - 50053:50053
    restart: always
