version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    ports:
      - "${SCALAR_PORT}:${SCALAR_PORT}"
      - "${SCALAR_PRIVILEGED_PORT}:${SCALAR_PRIVILEGED_PORT}"
      - "50053:50053"
    env_file:
      - container.env
    restart: always
