version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    env_file:
      - container.env
    ports:
      - 50051:50051 # TODO: SCALAR_PORT
      - 50052:50052 # TODO: SCALAR_PRIVILEGED_PORT
      - 50053:50053
    restart: always
