version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    environment:
      - SCALAR_DB_CONTACT_POINTS=${SCALAR_CASSANDRA_HOST}
      - SCALAR_DB_USERNAME=${SCALAR_CASSANDRA_USERNAME}
      - SCALAR_DB_PASSWORD=${SCALAR_CASSANDRA_PASSWORD}
    ports:
      - 50051:50051 # TODO: SCALAR_PORT
      - 50052:50052 # TODO: SCALAR_PRIVILEGED_PORT
      - 50053:50053
    restart: always
