version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    ports:
      - "${SCALAR_PORT}:${SCALAR_PORT}"
      - "${SCALAR_PRIVILEGED_PORT}:${SCALAR_PRIVILEGED_PORT}"
      - "50053:50053"
    environment:
      - SCALAR_DB_STORAGE=${SCALAR_DB_STORAGE}
      - SCALAR_DB_CONTACT_POINTS=${SCALAR_DB_CONTACT_POINTS}
      - SCALAR_DB_CONTACT_PORT=${SCALAR_DB_CONTACT_PORT}
      - SCALAR_DB_USERNAME=${SCALAR_DB_USERNAME}
      - SCALAR_DB_PASSWORD=${SCALAR_DB_PASSWORD}
    restart: always
