version: '3.7'

services:
  scalar:
    build:
      context: ./
      args:
        - FROM_SCALAR_IMAGE=${FROM_SCALAR_IMAGE}
    image: ${SCALAR_IMAGE}
    environment:
      - SCALAR_CASSANDRA_HOST=${SCALAR_CASSANDRA_HOST}
      - SCALAR_CASSANDRA_USER=${SCALAR_CASSANDRA_USER}
      - SCALAR_CASSANDRA_PASSWORD=${SCALAR_CASSANDRA_PASSWORD}
      - CASSANDRA_REPLICATION_FACTOR=${CASSANDRA_REPLICATION_FACTOR}
    ports:
      - 50051:50051 # TODO: SCALAR_PORT
      - 50052:50052 # TODO: SCALAR_PRIVILEGED_PORT
      - 50053:50053
    restart: always
