version: '3.7'

services:
  scalar:
    image: ${SCALAR_IMAGE}
    environment:
      - SCALAR_DB_STORAGE=${SCALAR_DB_STORAGE}
      - SCALAR_DB_CONTACT_POINTS=${SCALAR_DB_CONTACT_POINTS}
      - SCALAR_DB_CONTACT_PORT=${SCALAR_DB_CONTACT_PORT}
      - SCALAR_DB_USERNAME=${SCALAR_DB_USERNAME}
      - SCALAR_DB_PASSWORD=${SCALAR_DB_PASSWORD}
      # For ledger.properties in scalar-ledger container
      - SCALAR_DL_LEDGER_SERVER_PORT=50051
      - SCALAR_DL_LEDGER_SERVER_PRIVILEGED_PORT=50052
      - SCALAR_DL_LEDGER_SERVER_ADMIN_PORT=50053
    env_file:
      - container.env
    ports:
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
    restart: always
