version: "3.7"

services:
  scalar:
    build:
      context: ./
      args:
        - FROM_SCALAR_IMAGE=${FROM_SCALAR_IMAGE}
    image: ${SCALAR_IMAGE}
    environment:
      - SCALAR_DB_CONTACT_POINTS=${SCALAR_CASSANDRA_HOST}
      - SCALAR_DB_USERNAME=${SCALAR_CASSANDRA_USERNAME}
      - SCALAR_DB_PASSWORD=${SCALAR_CASSANDRA_PASSWORD}
      - CASSANDRA_REPLICATION_FACTOR=${CASSANDRA_REPLICATION_FACTOR}
      - SCALAR_IMAGE_TAG=${SCALAR_IMAGE_TAG}
    ports:
      - 50051:50051 # TODO: SCALAR_PORT
      - 50052:50052 # TODO: SCALAR_PRIVILEGED_PORT
      - 50053:50053
    restart: always
