{
 "title": "Scalar Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "label_values(node_systemd_system_running, job)"
   }
  ]
 },
 "panels": [
  { "title": "${Job} Cluster", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "repeat": "Job" },
  { "title": "${Job} Cluster", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "${Job} Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "Job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_systemd_system_running{job=~\"$Job\"})"
    }
   ]
  },
  {
   "title": "${Job} Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_systemd_system_running{job=~\"$Job\"})"
    }
   ]
  },
  {
   "title": "${Job} Server Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "repeat": "Job",
   "targets": [
    {
     "expr": "node_systemd_system_running{job=\"$Job\"}"
    }
   ]
  },
  {
   "title": "${Job} Server Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "node_systemd_system_running{job=\"$Job\"}"
    }
   ]
  },
  {
   "title": "${Job} Service",
   "type": "singlestat",
   "description": "The percent of nodes with an active ${Job} service",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "repeat": "Job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{name=~\"$Job.service\", state=\"active\"})/sum(node_systemd_system_running{job=~\"$Job\"})*100\n"
    }
   ]
  },
  {
   "title": "${Job} Service",
   "type": "singlestat",
   "description": "The percent of nodes with an active ${Job} service",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{name=~\"$Job.service\", state=\"active\"})/sum(node_systemd_system_running{job=~\"$Job\"})*100\n"
    }
   ]
  },
  {
   "title": "${Job} Service",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "repeat": "Job",
   "targets": [
    {
     "expr": "sort_desc(node_systemd_unit_state{name=~\"$Job.service\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "${Job} Service",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(node_systemd_unit_state{name=~\"$Job.service\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "repeat": "Job",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", job=~\"$Job\"}[1m])) or sum(irate(node_cpu{mode=\"idle\", job=~\"$Job\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", job=~\"$Job\"}[1m])) or sum(irate(node_cpu{mode=\"idle\", job=~\"$Job\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 17 },
   "repeat": "Job",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_Active_bytes{job=~\"$Job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$Job\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_Active_bytes{job=~\"$Job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$Job\"})) * 100"
    }
   ]
  }
 ]
}