---
# Docker options.
docker_packages:
  - docker-ce
  - containerd.io

# Docker Compose options.
docker_compose_version: "1.26.0"
docker_compose_path: /usr/local/bin/docker-compose
docker_compose_file: docker-compose-Linux-x86_64
docker_compose_download: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/{{ docker_compose_file }}"
docker_compose_checksum: "{{ docker_compose_download }}.sha256"

# Used only for Debian/Ubuntu.
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

# A list of users who will be added to the docker group.
docker_users:
  - "{{ ansible_user_id }}"

# cAdvisor options
cadvisor_version: v0.35.0
cadvisor_checksum: >-
  e9bb5513d9c49741a6ccf9ec0ce68a0ca5d25d8e75cb426c525b003fbf19cdd9
cadvisor_url: https://github.com/google/cadvisor/releases/download/
cadvisor_download: "{{ cadvisor_url }}/{{ cadvisor_version }}/cadvisor"
