---
- name: Ensure pip3 is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Install Ansible
  pip:
    name: ansible
    state: present
    version: "{{ ansible_version }}"
    executable: "{{ pip_executable }}"
