name: Terraform test for CA module of AWS Example

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/aws/ca/**
      - modules/universal/ca/**
      - examples/aws/ca/**
      - provision/ansible/**
  push:
    branches:
      - master
    paths:
      - modules/aws/ca/**
      - modules/universal/ca/**
      - examples/aws/ca/**
      - provision/ansible/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./examples/aws/ca

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
