name: Integration test with terratest for AWS
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      # GOPATH: ${GITHUB_WORKSPACE}/test
      # GOBIN: ${GOPATH}/bin
      # PATH: ${PATH}:${GOBIN}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        # with:
        #   ref: master
      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u scalartest --password-stdin docker.io
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Download scalardl client sdk
        run: |
            curl -LO https://github.com/scalar-labs/scalardl-client-sdk/archive/v${SCALARDL_SDK_VERSION}.tar.gz
            tar -xvzf v${SCALARDL_SDK_VERSION}.tar.gz
            mv ./scalardl-client-sdk-${SCALARDL_SDK_VERSION} ./scalardl-client-sdk
        env:
          SCALARDL_SDK_VERSION: 1.3.0
        working-directory: ./test/src/integration
      - name: Set up GO
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.5
        id: go
      - name: Get dep
        run: |
            mkdir -p ${GOBIN}
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        env:
          GOPATH: ${GITHUB_WORKSPACE}/test
          GOBIN: ${GOPATH}/bin
        working-directory: ./test
      - name: Install terratest modules
        run: |
            dep ensure
        working-directory: ./test/src/integration
      - name: Install helper modules
        run: |
            dep ensure
        working-directory: ./test/src/modules
      - name: Create ssh key
        run: |
            eval `ssh-agent`
            ssh-keygen -N "" -t rsa -f terratest_key
            chmod 600 terratest_key
            ssh-add terratest_key
        working-directory: ./test/modules
      - name: Run terratest
        run: |
            go test -run TestEndToEnd -timeout 120m -args -directory="../../modules/awsdeploy/"
        working-directory: ./test/src/integration
