name: Terraform test for Pulsar module of AWS

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/aws/pulsar/**
  push:
    branches:
      - master
    paths:
      - modules/aws/pulsar/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.14.7
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Validate and Format
        run: |
          paths=(${GITHUB_WORKSPACE}/modules/aws/pulsar)
          for d in "${paths[@]}"; do cd ${d} && terraform init -backend=false && terraform validate -no-color && terraform fmt -check -recursive; done
