name: Terraform test for Pulsar module of AWS

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/aws/pulsar/**
  push:
    branches:
      - master
    paths:
      - modules/aws/pulsar/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./test/modules/awsdeploy/pulsar

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set up to using dummy local variables
        run: |
          rm -f remote.tf locals.tf
          mv locals.tf.dummy locals.tf

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./modules/aws/pulsar

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color
