name: Integration test with terratest for AWS
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  terratest:
    name: Terratest
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: add-github-actions-yml-for-terratest
      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u scalartest --password-stdin docker.io
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Download scalardl client sdk
        run: |
            curl -LO https://github.com/scalar-labs/scalardl-client-sdk/archive/v${SCALARDL_SDK_VERSION}.tar.gz
            tar -xvzf v${SCALARDL_SDK_VERSION}.tar.gz
            mv ./scalardl-java-client-sdk-${SCALARDL_SDK_VERSION} ./scalardl-client-sdk
        env:
          SCALARDL_SDK_VERSION: 2.0.3
        working-directory: ./test/src/integration
      - name: Set up GO
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.5
        id: go
      - name: Create ssh key
        run: |
            ssh-keygen -N "" -t rsa -f test_key <<<y
            chmod 600 test_key
        working-directory: ./test/modules
      - name: Install terratest modules and run terratest
        run: |
            export GOPATH=$(pwd)
            export GOBIN=${GOPATH}/bin
            export PATH=${PATH}:${GOBIN}
            eval `ssh-agent`
            ssh-add ./modules/test_key
            mkdir -p ${GOBIN}
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            cd ${GITHUB_WORKSPACE}/test/src/modules && dep ensure
            cd ${GITHUB_WORKSPACE}/test/src/integration && dep ensure
            go test -run TestEndToEnd -timeout 120m -args -directory="../../modules/awsdeploy/"
        working-directory: ./test
