name: Terraform test for Monitor module of Azure Example

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/azure/monitor/**
      - modules/universal/monitor/**
      - examples/azure/monitor/**
      - provision/ansible/**
  push:
    branches:
      - master
    paths:
      - modules/azure/monitor/**
      - modules/universal/monitor/**
      - examples/azure/monitor/**
      - provision/ansible/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./examples/azure/monitor

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
