name: Terraform test for Scalar DL module of Azure

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/azure/scalardl/**
      - modules/universal/scalardl/**
      - modules/universal/envoy/**
      - test/modules/azuredeploy/scalardl/**
      - provision/**
  push:
    branches:
      - master
    paths:
      - modules/azure/scalardl/**
      - modules/universal/scalardl/**
      - modules/universal/envoy/**
      - test/modules/azuredeploy/scalardl/**
      - provision/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./test/modules/azuredeploy/scalardl

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set up to using dummy local variables
        run: |
          rm -f remote.tf locals.tf
          mv locals.tf.dummy locals.tf

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./modules/azure/scalardl

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color
