name: Terraform test for Monitor module of Azure

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/azure/monitor/**
      - modules/universal/monitor/**
      - example/azure/monitor/**
      - provision/**
  push:
    branches:
      - master
    paths:
      - modules/azure/monitor/**
      - modules/universal/monitor/**
      - example/azure/monitor/**
      - provision/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./example/azure/monitor

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./modules/azure/monitor

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
