name: Terraform test for Network module of Azure

on:
  pull_request:
    branches:
      - master
    paths:
      - modules/azure/network/**
      - modules/universal/bastion/**
      - modules/universal/name-generator/**
      - examples/azure/network/**
      - provision/**
  push:
    branches:
      - master
    paths:
      - modules/azure/network/**
      - modules/universal/bastion/**
      - modules/universal/name-generator/**
      - examples/azure/network/**
      - provision/**

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.12.29
    defaults:
      run:
        working-directory: ./examples/azure/network

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: for d in . ../../../modules/azure/network ; do cd ${d} && terraform fmt -check -recursive ;done

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
