name: 'Terraform test for Network module of Azure'
on:
  pull_request:
    branches:
      - master
    paths:
      - 'modules/azure/network/**'
      - 'modules/universal/bastion/**'
      - 'modules/universal/name-generator/**'
      - 'test/modules/azuredeploy/network/**'
      - 'provision/**'
  push:
    branches:
      - master
    paths:
      - 'modules/azure/network/**'
      - 'modules/universal/bastion/**'
      - 'modules/universal/name-generator/**'
      - 'test/modules/azuredeploy/network/**'
      - 'provision/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './modules/azure/network'
          tf_actions_comment: true
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './test/modules/azuredeploy/network'
          tf_actions_comment: true
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './test/modules/azuredeploy/network'
          tf_actions_comment: true
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.19
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './test/modules/azuredeploy/network'
          tf_actions_comment: true
