version: '3.7'
services:
  cqlsh:
    image: scalar-cassandra-reaper:latest
    build:
      context: ./
    command: ["cqlsh", "--cqlversion=3.4.4", "${REAPER_CASS_CONTACT_POINTS}", "-e", "CREATE KEYSPACE reaper_db WITH replication = {'class': 'SimpleStrategy', 'replication_factor': ${CASSANDRA_REPLICATION_FACTOR} };"]
    restart: on-failure
  reaper:
    image: scalar-cassandra-reaper:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - cqlsh
    environment:
      - "REAPER_JMX_AUTH_USERNAME=${REAPER_JMX_AUTH_USERNAME}"
      - "REAPER_JMX_AUTH_PASSWORD=${REAPER_JMX_AUTH_PASSWORD}"
      - "REAPER_STORAGE_TYPE=${REAPER_STORAGE_TYPE}"
      - "REAPER_CASS_CONTACT_POINTS=[${REAPER_CASS_CONTACT_POINTS}]"
    restart: always
